foreground #c0c0c0
background #12131a

selection_foreground #12131a
selection_background #c3fbb3

cursor #c3fbb3

# normal
color0  #12131a
color1  #ffe6e3
color2  #c3fbb3
color3  #ffe5ee
color4  #c3fbb3
color5  #eaeaff
color6  #ffe5ee
color7  #ffffff

# bright
color8  #444654
color9  #ffe6e3
color10 #c3fbb3
color11 #ffe5ee
color12 #c3fbb3
color13 #eaeaff
color14 #ffe5ee
color15 #ffffff
